// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsyTaNfzegYb5SNCTdPagG04O42gvkFtw',
    appId: '1:448293348234:web:a36d01742e22245fca9e73',
    messagingSenderId: '448293348234',
    projectId: 'ecom2-f46f1',
    authDomain: 'ecom2-f46f1.firebaseapp.com',
    storageBucket: 'ecom2-f46f1.firebasestorage.app',
    measurementId: 'G-BG5M58V1D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUHfnq-8Nr1CFPOd3YhP2WYhSFKV6yZLA',
    appId: '1:448293348234:android:d27d2183f08e0fbaca9e73',
    messagingSenderId: '448293348234',
    projectId: 'ecom2-f46f1',
    storageBucket: 'ecom2-f46f1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsyTaNfzegYb5SNCTdPagG04O42gvkFtw',
    appId: '1:448293348234:web:b95abb3f999ce608ca9e73',
    messagingSenderId: '448293348234',
    projectId: 'ecom2-f46f1',
    authDomain: 'ecom2-f46f1.firebaseapp.com',
    storageBucket: 'ecom2-f46f1.firebasestorage.app',
    measurementId: 'G-X98MJ9T4TW',
  );
}
